# Workflow to demo installing a package and executing on a self-hosted runner

 name: file tree

 on:
   workflow_dispatch:

 jobs:

   file-tree:

     runs-on: self-hosted

     steps:
     - name: Install net-tools
       run: |
         sudo apt update
         sudo apt install net-tools
     
