name: Build Docker Image and Create Deployment
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    name: Build Docker Image and Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        run: |
          pwd
          rm -rfv {*,.*}
          git clone https://github.com/z3rg/BulkyWeb.git .
          ls -lah
      - name: Build Docker Image
        run: |
          whoami
          id
          pwd
          rm -rf vuln.json
          docker images
          docker rmi --force asp_core
          docker build -t asp_core .
      - name: Docker Vulnerability Scanning using Trivy
        run: |
          docker images
          trivy image --format cosign-vuln -o vuln.json asp_core:latest
      - name: Docker Vulnerability Scanning using Trivy
        run: |
          ls -lah vuln.json
          COSIGN_EXPERIMENTAL=1 cosign attest --type vuln --predicate vuln.json asp_core:latest


     
