name: Build Docker Image and Create Deployment
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    name: Build Docker Image and Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        run: |
          rm -rf BulkyWeb
          git clone https://github.com/z3rg/BulkyWeb.git .
          ls -lah
      - name: Build Docker Image
        run: |
          whoami
          id
          pwd
          docker build -t asp_core .
          docker tag asp_core daniespahlevi/asp_core:latest
      
     
