name: Build Docker Image and Create Deployment
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    name: Build Docker Image and Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        run: |
          pwd
          shopt -s dotglob
          rm -rfv *
          shopt -u dotglob
          git clone https://github.com/z3rg/BulkyWeb.git .
          ls -lah
      - name: Build Docker Image
        run: |
          whoami
          id
          pwd
          rm -rf vuln.json
          docker images
          docker rmi --force asp_core
          docker build -t asp_core .
      - name: Docker Vulnerability Scanning using Trivy
        run: |
          docker images && trivy image --format cosign-vuln -o vuln.json asp_core:latest
      - name: Docker Create Attestetion using Cosign to docker registry
        run: |
          rm -rf cosign.*
          ls -lah vuln.json
          docker login -u daniespahlevi -p dckr_pat_cEep70ETQ1KCBQSgbq1r7RKJuro
          docker tag asp_core:latest docker.io/daniespahlevi/asp_core:latest
          docker push docker.io/daniespahlevi/asp_core:latest
          COSIGN_PASSWORD=password.1 cosign generate-key-pair
          yes | COSIGN_PASSWORD=password.1 cosign attest --key cosign.key --type vuln --predicate vuln.json docker.io/daniespahlevi/asp_core:latest 

     
